### ISSUE TITLE
What is this?! :D

### ISSUE THREAD

**Issue by ewerybody** [AlsonEntuna/MayaVaccineVirusRemover#1]
Whow I never knew there were Maya Viruses?!
I mean I was doing loads of evil stuff with MEL already back in the days but I couldn't have imagined the need for a removal tool!
👍👍👍
cheers:
ëRiC

**Comment by AlsonEntuna** [comment]
Yes, surprisingly, there was a "tool" that supposedly was like a vaccine but later on was considered to be a virus. Even Autodesk treated it as a virus 🤣🤣🤣
